name: Deploy Project
on:
  workflow_dispatch:
    inputs:
      project-name:
        description: "The name of the project to deploy"
        required: true

permissions:
  contents: read
  pull-requests: read

jobs:
  deploy-terraform:
    name: Deploy Terraform
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      project: ${{ inputs.project-name }}
    secrets: inherit
